# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

os: osx
language: ruby
cache: bundler

# don't build twice
if: tag IS blank

env:
  global:
    - TRAVIS_TAG=ursabot-197-travis-homebrew-cpp-autobrew
    - ARROW_FORMULA=./arrow/r/tools/apache-arrow.rb

before_script:
- git clone --no-checkout https://github.com/apache/arrow arrow
- git -C arrow fetch -t https://github.com/apache/arrow refs/pull/5360/merge
- if [ $CROSSBOW_USE_COMMIT_ID == true ]; then git -C arrow checkout c5754dd9544462e72ff945915b135532cfc7bec9; else git -C arrow checkout FETCH_HEAD; fi
- brew update
- brew audit $ARROW_FORMULA
script:
- brew install -v --build-from-source --HEAD $ARROW_FORMULA
- brew test $ARROW_FORMULA

notifications:
  email:
    - ursabot@ci.ursalabs.org